// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_connectfourgame.cpp"
#include "EWIEGA46WW/moc_fivexfivegame.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_normalgame.cpp"
#include "EWIEGA46WW/moc_pyramidgame.cpp"
